let tokenD = canvas.tokens.get(args[0].tokenId);
new Sequence()
    .effect()
        .file("jb2a.magic_signs.rune.abjuration.intro.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.abjuration.loop.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.abjuration.outro.blue")
        .scale(0.3)
        .atLocation(tokenD)
    .play()