let tokenD = canvas.tokens.get(args[0].tokenId);
let targetD = Array.from(game.user.targets)[0];
new Sequence()
    .effect()
        .file("jb2a.magic_signs.rune.divination.intro.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
 .effect()
        .file("jb2a.extras.tmfx.inpulse.circle.04.normal")
        .scale(0.3)
        .atLocation(targetD)
        .fadeIn(100)
        .fadeOut(100)
    .effect()
        .file("jb2a.magic_signs.rune.divination.loop.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .duration(500)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.divination.outro.blue")
        .scale(0.3)
        .atLocation(tokenD)
    .play()