let tokenD = canvas.tokens.get(args[0].tokenId);
let targetD = Array.from(game.user.targets)[0];
new Sequence()
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.intro.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.energy_strands.range.standard.purple")
        .gridSize(1)
        .atLocation(tokenD)
        .reachTowards(args[0].targets[0])
        .missed(args[0].hitTargets.length === 0)
        .filter("Glow", { color: 0x0000ff})
        .waitUntilFinished(-1200)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.loop.blue")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .waitUntilFinished(-550)
        .duration(500)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.outro.blue")
        .scale(0.3)
        .atLocation(tokenD)
    .play()