let tokenD = canvas.tokens.get(args[0].tokenId);
new Sequence()
    .effect()
        .file("jb2a.detect_magic.circle.purple")
        .scale(0.2)
        .atLocation(tokenD)
        .duration(4000)
        .fadeIn(100)
        .fadeOut(100)
        .filter("Blur", { blurX: 20, blurY: 20 })
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.intro.purple")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.loop.purple")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .waitUntilFinished(-550)
        .duration(800)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.outro.purple")
        .scale(0.3)
        .atLocation(tokenD)
    .play()