let tokenD = canvas.tokens.get(args[0].tokenId);
new Sequence()
    .effect()
        .file("jb2a.energy_strands.complete.purple.01")
        .scale(0.4)
        .atLocation(tokenD)
        .duration(4000)
        .fadeIn(500)
        .fadeOut(500)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.intro.purple")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.loop.purple")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .waitUntilFinished(-550)
        .duration(800)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.outro.purple")
        .scale(0.3)
        .atLocation(tokenD)
    .play()