const casterId = canvas.tokens.get(args[0].tokenId);
new Sequence()
    .effect()
        .file("jb2a.fire_bolt.orange")
        .atLocation(casterId)
        .reachTowards(args[0].targets[0])
        .missed(args[0].hitTargets.length === 0)
        .filter("Glow", { color: 0xffffff })
        .waitUntilFinished()
    .play()