const casterId = canvas.tokens.get(args[0].tokenId);
const targetId = Array.from(game.user.targets)[0];
new Sequence()
    .effect()
        .file("jb2a.magic_signs.rune.evocation.intro.yellow")
        .scale(0.3)
        .atLocation(casterId)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.divine_smite.caster.blueyellow")
        .atLocation(targetId)
        .scale(0.5)
        .belowTokens()
        .fadeOut(1000)
        .duration(1500)
    .effect()
        .file("jb2a.explosion.blue.2")
        .atLocation(targetId)
        .scale(0.5)
    .effect()
        .file("jb2a.magic_signs.rune.evocation.outro.yellow")
        .scale(0.3)
        .atLocation(casterId)
    .play()