let tokenD = canvas.tokens.get(args[0].tokenId);
let targetD = Array.from(game.user.targets)[0];
new Sequence()
    .effect()
        .file("jb2a.butterflies.many.green")
        .scale(0.4)
        .atLocation(tokenD)
        .duration(4000)
        .fadeIn(100)
        .fadeOut(100)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.intro.green")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.loop.green")
        .scale(0.3)
        .atLocation(tokenD)
        .fadeIn(100)
        .fadeOut(100)
        .waitUntilFinished(-550)
        .duration(800)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.outro.green")
        .scale(0.3)
        .atLocation(tokenD)
    .effect()
        .file("jb2a.greatclub.green")
        .atLocation(tokenD)
        .reachTowards(args[0].targets[0])
        .missed(args[0].hitTargets.length === 0)
        .waitUntilFinished(-1200)
    .play()
