let tokenD = canvas.tokens.get(args[0].tokenId);
new Sequence()
.effect()
        .file("jb2a.magic_signs.circle.02.transmutation.outro.red")
        .scale(0.4)
        .atLocation(tokenD)
        .duration(3500)
        .scaleIn(0, 500, {ease: "easeOutCubic", delay: 100})    
        .fadeIn(100)
        .fadeOut(100) 
        .belowTokens()  
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.intro.red")
        .scale(0.3)
        .atLocation(tokenD)
        .waitUntilFinished(-550)
    .effect()
        .file("jb2a.magic_signs.rune.transmutation.outro.red")
        .scale(0.3)
        .atLocation(tokenD)
    .play()