let tokenD = canvas.tokens.get(args[0].tokenId);
new Sequence()
    .effect()
        .file("jb2a.butterflies.many.green")
        .scale(0.4)
        .atLocation(tokenD)
        .duration(2500)
        .fadeIn(200)
        .fadeOut(200)    
    .effect()
        .file("jb2a.magic_signs.rune.conjuration.intro.green")
        .scale(0.3)
        .atLocation(tokenD)
    .effect()
        .file("autoanimations.range.scorchingray.01.green")
        .atLocation(tokenD)
        .reachTowards(args[0].targets[0])
        .missed(args[0].hitTargets.length === 0)
        .filter("Glow", { color: 0x8cbb3a })
        .waitUntilFinished()
    .play()